apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreless-ui
  labels:
    app: bian-coreless-ui
spec:
  selector:
    matchLabels:
      app: bian-coreless-ui
  template:
    metadata:
      labels:
        app: bian-coreless-ui
    spec:
      containers:
        - name: coreless-ui
          image: quay.io/ecosystem-appeng/coreless-ui:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: $(CORELESS_UI_SERVICE_PORT)
            - name: CO_SERVICE_HOST
              value: 'customer-offer-http-route'
            - name: CO_SERVICE_PORT
              value: '8080'
            - name: PRP_SERVICE_HOST
              value: 'party-routing-profile-camelk-rest'
            - name: PRP_SERVICE_PORT
              value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: coreless-ui
  labels:
    app: bian-coreless-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: bian-coreless-ui